### ISSUE TITLE
Unexpected inlay clipping

### ISSUE THREAD

**Issue by maxkahnt** [propjockey/augmented-ui#12] opened 2020-11-03 15:28 UTC
I am continuing the following issue here: 

2. In order for the separate inlay to respect the border when they're split up, you'll have to manually add the --aug-border-[pos] values to the --aug-inlay-[pos] values. Inlay does not consider any of the border values unless the border is enabled.
You _could_ just add `both` on the inlay instead and give the border a transparent bg, but it's already pretty heavy so that's a trade off for your consideration

_Originally posted by @James0x57 in https://github.com/propjockey/aug-compile/issues/1#issuecomment-720805902_

Manually adding the values worked in my case.

~~The `both` option did not help as the interior was still overlapping the boundary (or at least a gap I'd like to have between inlay and border).~~(I am not confident that I tested that thorougly, either way I felt like I end up setting the variables anyway, which already does the trick without transparent border.)
I suppose my problem is related to the `background` property being set on an `inlay`-augmented element not behaving the same as if I was invoking `--aug-inlay-bg`.

As the manual adding is working and I managed to _work around_ the background issue, this issue is not _pressing_ by any means ;). 

Augmented-UI interface
---
I wonder what could be the use case for --aug-inlay-bg. Is it just technical to get hold of the value as it cannot be read from the actual `background` property? If not, then the same could be done for the border which could decrease the amount of exposed css variables by a lot (and rely on border, background, padding only, merely extending it by your clipping system). From my current viewpoint, the `augmented-ui` interface would be cleaner if it would behave like a css element in `content-box` mode w.r.t. the background. 

Disclaimer
---
Let me re-emphasize that you already helped me a ton and that in general I am satisfied with the results. I start nitpicking now as this has sparked some interest on my side and I am probably abusing the issue functionality for that. Maybe this outside input helps you to advance your module, which would be awesome. Maybe I start getting on your nerves, then I don't mind if you just drop this ;)

**Comment by James0x57** [comment] 2020-11-03 20:26
haha, lots of details here, and a pretty heavy context for this conversation, I'll try to respond to everything:

> I suppose my problem is related to the background property being set on an inlay-augmented element not behaving the same as if I was invoking --aug-inlay-bg.

This is in relation to aug-compile where it computes the --aug-inlay-bg property on compile. If you set `::before { background... }` instead of using the property, many browsers cannot get the computed value of the `background` property so it must use the --aug-inlay-bg custom property. This is the difference. It is working as intended. **Solution**: do not manually set augmented border or inlay backgrounds, always use the provided properties instead.

> I wonder what could be the use case for --aug-inlay-bg. ....

As for why I provided `--aug-inlay-bg` and `--aug-border-bg`, it's so you can set the background of pseudo elements from the parent the same way you set their other properties without worrying about the implementation detail of what pseudo element belongs to what feature. It's also much cleaner in the end user;s CSS since you don't have to duplicate the selector.
(actually setting the inlay distances/border sizes on the parent is necessary so inlay can be inlayed from the edge of the border when there is one, which is otherwise impossible without duplicate CSS for the end user)

The backgrounds behave identically/consistently across the element, border, and inlay and do not change behavior no matter what box-sizing the user decides to use. Can't get cleaner than that IMO.\\

...this is all a bit long-winded already, but you've been interested in the details and shared many more thoughts, so I'll go even further to try to be specific about the design decisions and considerations I've made:

----

Augmented borders and inlays are both implemented as (optional) pseudo elements covering the full size of the element, clipped with respect to the augs applied to it. The inner edge of a border and the edge of an inlay are a mathematical degradation of the element's augmented shape. This allows complex backgrounds to align perfectly as a default behavior without deliberate effort to the end user. 
The standard CSS `border` and `padding` properties are not part of augmented-ui at all.

I have considered padding, and a shape-around feature, but both only end up being annoying to the end user who will place their content within an augmented element wherever and however they want.
99% of the time they'll be setting the element's padding to something slightly larger than the distance from the element edge to the inlay edge anyway (so there appears to be padding between the inlay edge and content), so it would have been wasted effort for me, the users, and the browser's rendering engine if I set defaults that will always be overwritten.

All this also ignores the fact that the padding a user adds to their element is also going to depend on what augs are equipped to the corresponding edge or corner and will, in turn, affect their design's padding decision in non-deterministic ways. This is the main reason I'll probably never add anything that messes with the natural CSS padding. As it is now, users always have full control, control that doesn't require extra library-specific knowledge to consider (nobody wants another bootstrap.css fight every time they work on a site)

----

Anyway, I'm going to close this. I promise, you are not getting on my nerves at all, haha Feel free to re-open or continue making your case if you don't feel like I've considered your position well enough. I am open to making changes but a padding proposal is a big deal and will be a very hard sell to me and to existing users.
Plus, you can always roll your own general-case padding solution as an add-on. Use a `[data-augmented-ui]` selector and play around with your ideas. If you come up with something that meets 90% of your expectation in practice, I'd say it's worth serious consideration, or possibly just a link to your addon from the homepage :)

**Closed by James0x57** 2020-11-03 20:26 UTC

**Comment by maxkahnt** [comment] 2020-11-03 22:18
And here I am again ;) Let me stress again that I come with the best intentions and I don't want you to feel like you need to defend yourself - it's hard to judge from just reading these lines. I really really appreciate your module AND the effort you put into your answers here. :100: 

Here is an example to clarify my issue: https://codepen.io/maxkahnt/pen/wvWXjJb
Maybe I am just misusing the framework, but to me this seems like an unintentional behavior.

---

I have some opinions on the other stuff as well, but maybe it is not worth discussing until this is resolved, because it heavily relates. I feel misunderstood slightly (and re-reading my comment I can understand why) and might eventually elaborate.

**Comment by James0x57** [comment] 2020-11-04 00:17
ohhhh a picture is worth 1000 words - I see what your fundamental concern was now.

Good news, if you intentionally want to clip a child as if it was the inlay, that's exactly why I added the `delegated-inlay` option. Most commonly I'd expect a delegate inlay to be an `img` tag so you can make neat picture frames with a gap to the border. Anyway, just slightly tweak what you have by adding what I've highlighted in this image and the inlay will be delegated to your content container:
![image](https://user-images.githubusercontent.com/7545075/98054282-2a184900-1e00-11eb-9e76-ed63f819d488.png)

btw: technically the content is clipped by the element's clip path, the border is just rendering on top of it :)

**Comment by maxkahnt** [comment] 2020-11-04 09:24
Great!!

So I'm back to delegates (which in this setting fortunately seem to work in conjunction with `aug-compile`). Since I insert my content dynamically I had to insert another div to carry the data-augmented-ui-inlay and set `position: relative` for it. (`absolute` seems to be the default in your module. Do you use it enforce a new stacking context? If so, shouldn't his be already the case due to clip-path?)

Now allow me to come back to my more general remarks, given that I can fiddle with the `aug-compile` result. I did not try these things out in `both` mode but only with my specific setup above. Maybe my notes do not generalize to `both` mode in straightforward fashion, but they nice illustrate my remarks. Creating examples is a lot of fiddling on my side, so let my try with descriptions again first. I'll work out examples on Codepen if necessary.

Border
---
Inspecting the CSS for the data-augmented-ui-comiled="border" element, I can see two `clip-path`'s (one being in the `after` pseudo element). Disabling the `after` has the shadow appear much more intense, supposedly this is the _right_ one.

Inlay
---
For the inlay: If I copy the CSS of the `before` pseudo element (`clip-path`, `opacity`, `background` in my case) to the regular element, I obtain the same visual result. (If this behavior was the default, it would render the inlay delegation obsolete and allow to set the inlay background via regular CSS instead of a custom variable. If you explained above why this is not working, I have not understood it.)

**Comment by maxkahnt** [comment] 2020-11-04 12:29
I have trouble coming up with a Codepen example, because `aug-compile` does seem to break things (still/again). It is not happening for my project. Is the unpkg archive updated already?

https://codepen.io/maxkahnt/pen/yLJEWBM

**Comment by maxkahnt** [comment] 2020-11-04 13:24
One more: One of my use cases is in fact an image. I can get rid of the custom `inlaystyle` argument (https://github.com/propjockey/aug-compile/issues/1#issuecomment-720739501) in favor of the delegated-inlay, if I wrap my entire module again in a size-imposing element.
This is probably more of general CSS question, but it stems from the general workaround of having to separate border and inlay in the first place. I modified my example to show the issue: codepen.io/maxkahnt/pen/wvWXjJb

**Comment by James0x57** [comment] 2020-11-04 13:44
**Re: position**
The inlay is meant to be a background, `position: absolute;` removes it from the content flow. This is intentional. If you choose to use the inlay as a content container, then of course change it to `position: relative;` in your css

**Re: Border**
The shadow is more intense if you disable the inner clip (on ::after) because you're then drawing the full element instead of just the borders... Disabling the clip on after is practically the same as disabling the border. If you want that effect, don't use `border` and instead just set background on the augmented element directly.

**Re: Inlay**
I don't understand what you're saying at all. aug-compile does not work with delegates right now, I'll fix it this weekend

**Re: Fiddling**
There should be absolutely no difference between normal and minified, I would suspect you're compiling before the css has loaded and that it's a race condition you're seeing.

**Re: Codepen**
Try this? https://jsfiddle.net/q2ouz6L8/

**Re: Image**
https://jsfiddle.net/qcLvtdsm/

**Comment by maxkahnt** [comment] 2020-11-04 14:55
Wow, you're quick, structured and precise.

_The inlay is meant to be background._ That clicked. `augmented-ui` provides an additive declaration to any element, hence you prepend and append relatively unimpactful pseudo elements for styling purposes. That makes a lot of sense! And your documentation also refers to delegation as a tool to put content. Which is what I want. I just did not understand that right away.

**Re: Border:** That makes sense. The full element interior is not visible due to the clip-path that is copied to the parent in my case, but it presumably impacts the drop-shadow computation on it.

**Re: Image:** ~~I tried to convey that I want to have an augmented container that adapts in size to whatever content it gets. It seems to work for height but fails for width. Your example exhibits image width 100% and breaks if I set it to anything else. I don't mind wrapping the `<img>` if that helped, but I'd prefer not wrapping the container-div to impose adaptive sizing.~~ (Still working on it, consider this comment temporary.)

**Re: Inlay:** I'm looking forward to the `aug-compile` update.

**Re: Fiddling:** _... trying to figure out what went wrong on my end here then ..._

**Re: Codepen:** What is this intending to show? Once the compile step is through (which takes a while for me), the inlay looks broken again.

**Comment by James0x57** [comment] 2020-11-04 15:33
**Re: Image**
If you want a container to be sized according to its content, set its display to inline-block: https://jsfiddle.net/71svpzy5/

I'll check back around lunch, gotta continue at work for now but I think that's the last thing you needed help with until I update aug-compile to work with delegates?

**Comment by maxkahnt** [comment] 2020-11-04 15:45
Yes. I feel blessed ;)
