### ISSUE TITLE
Invalid CSS in 1176, 1248, 1299

### ISSUE THREAD

**Issue by bencelaszlo** [propjockey/augmented-ui#2] opened 2019-10-08 17:57 UTC
I am using augmented-ui with vue (and its cli-service). The problematic pattern is repeated in the three lines:
`(--foo: , 0 0)`

If I delete the commas, then the problems gone.

**Comment by James0x57** [comment] 2019-10-09 03:08
Hey @bencelaszlo thank you for the issue

This is a bug in the parser your project is relying on, the CSS is not invalid.

(Leading comas in css variables is not invalid, and those specific lines are @supports statements so should doubly not be causing a problem in whatever parser it is.)

I assume you're running into your error during a build/minification?

Do you have a repo and/or steps to reproduce the specific issue you ran into? And a copy of the error message? I can fix it in their parser or at least submit an issue for them.

Any info you can provide will be helpful - I might even be able to give you a temporary work around by skipping the buggy parser and including/bundling the augmented-ui file directly.

**Comment by bencelaszlo** [comment] 2019-10-09 17:59
No, I'm getting these errors using VSCode:
`property value expected css(css-property value expected)`

**Comment by James0x57** [comment] 2019-10-09 20:37
Okay, looks like VSCode's built in CSS linter is wrong:
![image](https://user-images.githubusercontent.com/7545075/66518025-e4c50300-eaa9-11e9-946c-a440d1090e3e.png)

Is this the only error you were talking about?

Does it prevent anything in your project from working?

**Comment by James0x57** [comment] 2019-10-09 20:40
![image](https://user-images.githubusercontent.com/7545075/66518511-07a3e700-eaab-11e9-9589-77eb7e014cc0.png)
https://code.visualstudio.com/docs/languages/css#_syntax-verification-linting

**Comment by James0x57** [comment] 2019-10-13 03:17
Filed an issue with VSCode - they'll take care of it: https://github.com/microsoft/vscode/issues/82178

Closing since you can disable VSCode's css verification until they fix it (if needed)

Please feel free to re-open or comment if you need additional help!

**Closed by James0x57** 2019-10-13 03:17 UTC
Labels: 3rd party parsing issue
